pipeline {
    agent any 
    stages {
        stage('Make the droe land') {
            steps {
                sh '''
                rostopic pub /drone/land std_msgs/Empty "{}" &
                LAND_ID=$!
                '''
            }
        }
        stage('Done') {
            steps {
                sh '''
                sleep 5s
                kill $LAND_ID
                echo "Pipeline completed"
                '''
            }
        }
    }
}