pipeline {
    agent any 
    stages {
        stage('Run tests') {
            steps {
                sh 'python ~/catkin_ws/src/move_and_turn/exam/test_drone_sim.py'
            }
        }
        stage('Make the droe land') {
            steps {
                sh '''
                rostopic pub /drone/land std_msgs/Empty "{}" &
                LAND_ID=$!
                sleep 5s
                kill $LAND_ID
                '''
            }
        }
        stage('Done') {
            steps {
                sh '''
                echo "Pipeline completed"
                '''
            }
        }
    }
}